### PR TITLE
Move to pure bash and more idempotency

### PR DESCRIPTION
**Pull request by seanclerkin**
Needs 5 thumbs up.

### CODE REVIEW

**Comment by mikesmithmsm** [comment]
:+1: :love_hotel:

**Comment by TristanPeers** [comment]
:+1: :+1: :+1: :+1: :+1:  5 thumbs from me...

**Comment by dstockton** [comment]
:+1:

**Comment by neilmassey** [comment]
:+1:

**Comment by chrisjomaron** [comment]
:+1:   and a little ditty:   

C cells, 
C shells, 
on the see, sure!

**Pull request merged**
